"""Add foreign key to Agent model

Revision ID: 2933fe2b2519
Revises: a898296a2423
Create Date: 2024-01-09 19:28:58.779906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2933fe2b2519'
down_revision = 'a898296a2423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_agents_company_id', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
