"""Add foreign key to News model

Revision ID: a898296a2423
Revises: 
Create Date: 2024-01-09 19:05:02.909592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a898296a2423'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_news_company_id', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('fk_news_company_id', type_='foreignkey')
        batch_op.drop_column('company_id')
    # ### end Alembic commands ###
    